apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- UI/service.yaml
- UI/deployment.yaml
- user/service.yaml
- user/deployment.yaml
- ingress/ingress.yaml
images:
- name: ui-image
  newName: gitlab.ddoksik2.site:5050/bangwol08/healthcare_front/uiservice
  newTag: 3e669665
- name: user-image
  newName: gitlab.ddoksik2.site:5050/bangwol08/healthcare_backend/user
  newTag: 60f99bb5
namespace: default
