apiVersion: v1
kind: Service
metadata:
  name: ui-svc
spec:
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: ui-image
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: gitlab-registry