apiVersion: apps/v1
kind: Deployment
metadata:
  name: diet-deploy
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diet
  template:
    metadata:
      labels:
        app: diet
    spec:
      containers:
      - name: diet
        image: diet-image
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: gitlab-registry